# .NET Core
# Build and run tests for .NET Core solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/zh-cn/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=dotnetfive

pool: 'Azure Self-Host Pipeline'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core Runtime 6.x'
  inputs:
    version: '6.0.x'
    packageType: runtime
    performMultiLevelLookup: true

- task: CmdLine@2
  displayName: 'Install PNPM'
  inputs:
    script: 'npm -g install pnpm'
    workingDirectory: 'Scyphozoa\ClientApp'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'
    feedsToUse: config
    nugetConfigPath: nuget.config 
    noCache: true

- task: CmdLine@2
  displayName: 'pnpm install'
  inputs:
    script: 'pnpm install'
    workingDirectory: 'Scyphozoa\ClientApp'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test $(buildConfiguration)'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'